name: IDL
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - absl-py=2.2.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.11.18=py39hefdd603_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - anyio=4.9.0=pyh29332c3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py39h06df861_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=pyhd8ed1ab_3
  - async-lru=2.0.5=pyh29332c3_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - atk-1.0=2.36.0=h7fe96df_0
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.7.11=ha4ce7b8_1
  - aws-c-cal=0.6.9=h4fd42c2_3
  - aws-c-common=0.9.12=h93a5062_0
  - aws-c-compression=0.2.17=h4fd42c2_8
  - aws-c-event-stream=0.4.1=he66824e_2
  - aws-c-http=0.8.0=hd3d28cd_2
  - aws-c-io=0.14.0=h8daa835_1
  - aws-c-mqtt=0.10.1=h59ff425_0
  - aws-c-s3=0.4.9=h7f99a2c_0
  - aws-c-sdkutils=0.1.13=h4fd42c2_1
  - aws-checksums=0.1.17=h4fd42c2_7
  - aws-crt-cpp=0.26.0=hfff802b_8
  - aws-sdk-cpp=1.11.210=he93ac2d_10
  - azure-core-cpp=1.14.0=hd50102c_0
  - azure-identity-cpp=1.10.0=hc602bab_0
  - azure-storage-blobs-cpp=12.13.0=h7585a09_1
  - azure-storage-common-cpp=12.8.0=h9ca1f76_1
  - azure-storage-files-datalake-cpp=12.12.0=hcdd55da_1
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - bias_correction=0.4=pyhd8ed1ab_0
  - blas=2.131=openblas
  - blas-devel=3.9.0=31_h11c0a38_openblas
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.5=hc338f07_0
  - bokeh=3.4.2=pyhd8ed1ab_0
  - boltons=24.0.0=pyhd8ed1ab_1
  - bottleneck=1.4.2=py39hbda83bc_0
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - brotli-python=1.1.0=py39hfa9831e_2
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.2.25=hca03da5_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.2=pyhd8ed1ab_0
  - cairo=1.18.0=hc6c324b_2
  - cartopy=0.23.0=py39hc5ad87a_2
  - certifi=2025.1.31=py39hca03da5_0
  - cf_xarray=0.9.5=pyhd8ed1ab_0
  - cffi=1.17.1=py39h7f933ea_0
  - cftime=1.6.4=py39h914ef23_1
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - climpred=2.5.0=pyhd8ed1ab_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h85b62ae_2
  - cryptography=44.0.2=py39h558b0be_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.0.1=py39hf3bc14e_0
  - dask=2024.8.0=pyhd8ed1ab_0
  - dask-core=2024.8.0=pyhd8ed1ab_0
  - dask-expr=1.1.10=pyhd8ed1ab_0
  - debugpy=1.8.14=py39h941272d_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2024.8.0=pyhd8ed1ab_0
  - docrep=0.3.2=pyh44b312d_0
  - eofs=2.0.0=pyhff2d567_0
  - esmf=8.7.0=mpi_mpich_h5625ee3_101
  - esmpy=8.7.0=pyhecae5ae_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.6.4=h313beb8_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - flatbuffers=23.5.26=h13dd4ca_1
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h1383a14_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.57.0=py39hefdd603_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=hce30654_1
  - fribidi=1.0.10=h1a28f6b_0
  - frozenlist=1.5.0=py39hefdd603_1
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - gast=0.6.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.12=h7ddc832_0
  - geos=3.13.1=hc9a1286_0
  - gettext=0.23.1=h3dcc1bd_0
  - gettext-tools=0.23.1=h493aca8_0
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - glib=2.84.0=heee381b_0
  - glib-tools=2.84.0=h1dc7a0c_0
  - glog=0.6.0=h6da1cb0_0
  - gobject-introspection=1.78.1=py39hb338bcb_2
  - google-auth=2.39.0=pyhd8ed1ab_0
  - google-auth-oauthlib=1.2.2=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - graphite2=1.3.14=hc377ac9_1
  - graphviz=2.50.0=h54e2d63_4
  - grpcio=1.59.3=py39h047a24b_0
  - gtk2=2.24.33=hc999137_3
  - gts=0.7.6=hde733a8_3
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py39h9feac5e_100
  - harfbuzz=9.0.0=h1836168_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.3=mpi_mpich_h13a04de_9
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=hc8870d7_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_metadata=8.6.1=hd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.18.1=pyh707e725_3
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.4.2=py39hca03da5_0
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpickle=4.0.0=pyh29332c3_0
  - jsonpointer=3.0.0=py39h2804cbe_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - keras=2.15.0=pyhd8ed1ab_0
  - kiwisolver=1.4.7=py39h157d57c_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20230802.1=cxx17_h13dd4ca_0
  - libaec=1.1.3=hebf3989_0
  - libarrow=15.0.0=h4ce3932_0_cpu
  - libarrow-acero=15.0.0=h13dd4ca_0_cpu
  - libarrow-dataset=15.0.0=h13dd4ca_0_cpu
  - libarrow-flight=15.0.0=ha94d253_0_cpu
  - libarrow-flight-sql=15.0.0=h39a9b85_0_cpu
  - libarrow-gandiva=15.0.0=hf757142_0_cpu
  - libarrow-substrait=15.0.0=h7fd9903_0_cpu
  - libasprintf=0.23.1=h493aca8_0
  - libasprintf-devel=0.23.1=h493aca8_0
  - libblas=3.9.0=31_h10e41b3_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.13.0=h73640d1_0
  - libcxx=20.1.3=ha82da77_0
  - libdeflate=1.23=h5773f1b_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.6.4=h286801f_0
  - libfabric=2.1.0=hce30654_1
  - libfabric1=2.1.0=h5505292_1
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgd=2.3.3=hfdf3952_9
  - libgettextpo=0.23.1=h493aca8_0
  - libgettextpo-devel=0.23.1=h493aca8_0
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran5=14.2.0=h6c33f7e_103
  - libglib=2.84.0=hdff4504_0
  - libgoogle-cloud=2.12.0=hfb399a7_4
  - libgrpc=1.59.3=h9560976_0
  - libhwloc=2.11.2=default_h3f80f97_1000
  - libiconv=1.18=hfe07756_1
  - libintl=0.23.1=h493aca8_0
  - libintl-devel=0.23.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - liblapacke=3.9.0=31_hbb7bcf8_openblas
  - libllvm14=14.0.6=hd1a9a77_4
  - libllvm15=15.0.7=h2621b3d_4
  - liblzma=5.8.1=h39f12f2_0
  - libnetcdf=4.9.2=mpi_mpich_hf75f9b5_14
  - libnghttp2=1.64.0=h6d7220d_0
  - libopenblas=0.3.29=openmp_hf332438_0
  - libopentelemetry-cpp=1.13.0=hbaf25a0_0
  - libopentelemetry-cpp-headers=1.13.0=hce30654_0
  - libparquet=15.0.0=hf6ce1d5_0_cpu
  - libpnetcdf=1.13.0=mpi_mpich_h16bb634_101
  - libpng=1.6.47=h3783ad8_0
  - libprotobuf=4.24.4=h810fc01_0
  - libre2-11=2023.09.01=h741fcf5_1
  - librsvg=2.58.4=h40956f1_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.49.1=h3f77e49_2
  - libssh2=1.11.1=h9cc3647_0
  - libthrift=0.19.0=h026a170_1
  - libtiff=4.7.0=h551f018_4
  - libutf8proc=2.8.0=hc098a78_1
  - libwebp=1.5.0=h1618228_0
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.12.7=h9a80f22_3
  - libzip=1.11.2=h1336266_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.3=hdb05f8b_0
  - llvmlite=0.43.0=py39h313beb8_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py39h32162fe_1
  - lz4-c=1.9.4=hb7217d7_0
  - markdown=3.8=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py39hefdd603_1
  - matplotlib=3.9.4=py39hdf13c20_0
  - matplotlib-base=3.9.4=py39h7251d6c_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - ml_dtypes=0.2.0=py39h425d09f_2
  - mpi=1.0.1=mpich
  - mpich=4.3.0=h9d9a6ae_100
  - msgpack-python=1.1.0=py39h157d57c_0
  - multidict=6.4.3=py39hafbbd28_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - namex=0.0.9=pyhd8ed1ab_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nc-time-axis=1.4.1=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf-fortran=4.6.1=mpi_mpich_he94a790_8
  - netcdf4=1.7.2=nompi_py39h110e1d7_101
  - ninja=1.12.1=hca03da5_0
  - ninja-base=1.12.1=h48ca7d4_0
  - nlohmann_json=3.12.0=ha1acc90_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.60.0=py39h2d4ef1e_0
  - numexpr=2.10.1=py39h5d9532f_0
  - numpy=1.26.4=py39h3b2db8e_0
  - numpy-base=1.26.4=py39ha9811e2_0
  - oauthlib=3.2.2=pyhd8ed1ab_1
  - openblas=0.3.29=openmp_hea878ba_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openssl=3.5.0=h81ee809_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.15.0=py39he2d979d_0
  - orc=1.9.2=h7c018df_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py39hcf29cfe_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.54.0=h9ee27a3_2
  - parallelio=2.6.3=mpi_mpich_h24e929f_100
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=py39hca03da5_0
  - pcre2=10.44=h297a79d_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py39hfea3036_0
  - pint=0.24.4=pyhd8ed1ab_1
  - pip=25.0=py39hca03da5_0
  - pixman=0.44.2=h2f9eb0b_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.7=pyh29332c3_0
  - pooch=1.8.2=pyhd8ed1ab_1
  - proj=9.4.0=h52fb9d0_0
  - prometheus-cpp=1.1.0=hcd26875_1
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - propcache=0.3.1=py39hefdd603_0
  - properscoring=0.1=pyhd8ed1ab_1
  - protobuf=4.24.4=py39h6b23cf8_0
  - psutil=7.0.0=py39hf3bc14e_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=15.0.0=py39hb25a2a0_0_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_1
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycparser=2.22=pyh29332c3_1
  - pydot=3.0.4=py39hca03da5_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyobjc-core=11.0=py39hebff0d6_0
  - pyobjc-framework-cocoa=11.0=py39hebff0d6_0
  - pyopenssl=25.0.0=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyproj=3.6.1=py39h1c728a2_7
  - pyshp=2.3.1=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.18=hd7ebdb9_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-flatbuffers=25.2.10=pyhbc23db3_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=7_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyyaml=6.0.2=py39hefdd603_2
  - pyzmq=26.4.0=py39h80d5f2a_0
  - qhull=2020.2=h420ef59_5
  - re2=2023.09.01=h4cba328_1
  - readline=8.2=h1a28f6b_0
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=14.0.0=pyh29332c3_0
  - rpds-py=0.24.0=py39he565553_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - scikit-learn=1.6.1=py39h313beb8_0
  - scipy=1.13.1=py39hd336fd7_1
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=75.8.0=py39hca03da5_0
  - shapely=2.0.7=py39ha3f5d07_1
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.1.10=hd04f947_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - sparse=0.15.5=pyh72ffeb9_0
  - sqlite=3.49.1=hd7222ec_2
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py39h80987f9_0
  - tbb=2021.13.0=h8149167_1
  - tblib=3.1.0=pyhd8ed1ab_0
  - tensorboard=2.15.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py39h0ba8ec9_2
  - tensorflow=2.15.0=cpu_py39h89c7d27_2
  - tensorflow-base=2.15.0=cpu_py39ha39414a_2
  - tensorflow-estimator=2.15.0=cpu_py39ha1daed2_2
  - termcolor=3.0.1=pyhd8ed1ab_0
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.5.0=py39h33ce5c2_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.4.2=py39hf3bc14e_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025a=h04d1e81_0
  - unicodedata2=16.0.0=py39hf3bc14e_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py39hca03da5_0
  - wrapt=1.14.1=py39h02fc5c5_1
  - xarray=2024.7.0=pyhd8ed1ab_0
  - xclim=0.52.2=pyhd8ed1ab_0
  - xesmf=0.8.9=pyhd8ed1ab_0
  - xhistogram=0.3.2=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xrft=1.0.1=pyhd8ed1ab_1
  - xskillscore=0.0.26=pyhd8ed1ab_1
  - xyzservices=2025.1.0=pyhd8ed1ab_0
  - xz=5.6.4=h80987f9_1
  - yamale=5.3.0=pyhd8ed1ab_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.20.0=py39hefdd603_0
  - zeromq=4.3.5=hc1bb282_7
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=h8359307_2
  - zstandard=0.23.0=py39hf3bc14e_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - global-land-mask==1.0.0
prefix: /Users/tyler/anaconda3/envs/IDL
